# Generated by Django 4.0.3 on 2024-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_automobilevo_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
