# Generated by Django 4.0.3 on 2024-02-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_automobilevo_import_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sales_person',
            new_name='salesperson',
        ),
    ]
